#!/bin/bash

PATH=$1
FILENAME=$2
WEEK=$3
MONTH=$4

#uncooment to force month backup to be done anytime
#MONTH=1

#uncomment to trigger the compression of the whole backup for every single backup made
#COMPRESS_EVERY=1

CHMOD=/bin/chmod
TOUCH=/usr/bin/touch
RM=/bin/rm

LIST="$PATH/$FILENAME"


inc() {
    echo "+ ${@}" >> $LIST
}

exc() {
    echo "- ${@}" >> $LIST
}

cmt() {
    echo "# ${@}" >> $LIST
}

spt() {
    echo "" >> $LIST
}

trigger_compress() {
  cmt "This backup will be compressed as well"
  $TOUCH "$PATH/@compress_next_backup"
  $CHMOD a+rw $PATH/@compress_next_backup
}


if [ ! -f "$CHMOD" ] || [ ! -f "$TOUCH" ] || [ ! -f "$RM" ]; then
 $ECHO "Paths to tools (chmod touch rm) aren't setup properly."
 exit 1
fi


if [ -z "$LIST" ] || [ -z "$WEEK" ] || [ -z "$MONTH" ]; then
 echo "Usage: backup.sh LIST_FILENAME WEEKLY_BACKUP MONTHLY_BACKUP" >&2
 echo "  eg.: backup.sh backup.lst 0 1" >&2
 exit 1
fi


if [ "$COMPRESS_EVERY" = "1" ]; then
  #will trigger the whole backup compression for every single backup made
  trigger_compress
fi

$RM $LIST
$TOUCH $LIST
$CHMOD a+r $LIST

#this scripts writes warning to final file
cmt "Do not edit this file, it's generated by backup.sh script"

cmt "Include"
inc "/dev/console"
inc "/dev/initctl"
inc "/dev/null"
inc "/dev/zero"
spt

#exclude from every backup
cmt "Exclude"
exc "/dev/*"
exc "/proc/*"
exc "/opt/chrooted/proc/*"
exc "/sys/*"
exc "/tmp/*"
exc "*lost+found"
exc "/media/*"
exc "/mnt/*"
exc "/var/cache/*"
exc "/var/www/webdav/*-tmp/*"
exc "/home/user/.opera/*"
exc "/home/user/.nx/*"
exc "/home/user/.mozilla/*"


if [ "$MONTH" = "0" ] && [ "$WEEK" = "0" ]; then
    #exclude for daily backup (will not be exluded from weekly or monthly backups):
    # webalizer stats or less important content
    exc "/tmp"
    exc "/var/tmp/"
    exc "/var/lib/awstats/*"
    exc "/var/lib/munin/*"
    exc "/var/www/*/htdocs/webalizer_stats/*"
    exc "/var/www/*/logs/webalizer"
    exc "/var/www/*/logs/webalizer/*"
    exc "/var/www/*/logs/webalizer*.*"
    exc "/var/sqlite/selfoss-rss-citacka.sq3"
    exc "/var/sqlite/backups/selfoss-rss-*"
    #exc "/var/sqlite/backups/*"
fi

if [ "$MONTH" = "0" ]; then
    #exclude even more becuase it's not month backup
    exc "/opt/ventrilo/ventrilo_srv.log.*.gz"
    exc "/var/spool/*"
    exc "/var/run/*"
    exc "/var/log/*.gz"
    exc "/var/log/*.1"
    exc "/var/log/*/*.gz"
    exc "/var/log/*/*.1"
    exc "/var/www/*/logs/*.gz"
    exc "/var/backups/*.gz"
    exc "/var/lib/php5/*"
    exc "/var/lib/spamassassin/*"
    exc "/opt/framework-4.0.0/*"
else
    echo "Adding more items to backup (having less excluded folders), will add more logs, data files and any other files etc... to the list because it's monthly backup"

    #will trigger the compression of the whole backup
    trigger_compress
fi

